# Generated by Django 5.2.5 on 2025-08-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=56)),
                ('email_address', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=100)),
                ('service_needed', models.CharField(max_length=100)),
                ('budget_range', models.CharField(max_length=100)),
                ('project_details', models.TextField()),
            ],
        ),
    ]
